"""Alter Tables

Revision ID: 240b7aab707a
Revises: b1888a3fec38
Create Date: 2022-08-16 13:07:36.540224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240b7aab707a'
down_revision = 'b1888a3fec38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['Items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Contents_text'), 'Contents', ['text'], unique=False)
    op.create_table('Technologies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['Items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Technologies_url'), 'Technologies', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Technologies_url'), table_name='Technologies')
    op.drop_table('Technologies')
    op.drop_index(op.f('ix_Contents_text'), table_name='Contents')
    op.drop_table('Contents')
    # ### end Alembic commands ###
