"""Add CASCADE

Revision ID: 2a4f49f9a588
Revises: de08f73246f6
Create Date: 2022-08-26 10:14:45.477744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4f49f9a588'
down_revision = 'de08f73246f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
