"""Add image rows & cols

Revision ID: 3519ee64f429
Revises: 967a199ca0ee
Create Date: 2022-08-23 15:08:49.476105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3519ee64f429'
down_revision = '967a199ca0ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Images', sa.Column('rows', sa.Integer(), nullable=True))
    op.add_column('Images', sa.Column('cols', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Images_cols'), 'Images', ['cols'], unique=False)
    op.create_index(op.f('ix_Images_rows'), 'Images', ['rows'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Images_rows'), table_name='Images')
    op.drop_index(op.f('ix_Images_cols'), table_name='Images')
    op.drop_column('Images', 'cols')
    op.drop_column('Images', 'rows')
    # ### end Alembic commands ###
