"""Add links column

Revision ID: 6030a15a9779
Revises: 3519ee64f429
Create Date: 2022-08-24 15:21:42.860007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6030a15a9779'
down_revision = '3519ee64f429'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Contents', sa.Column('links', sa.String(), nullable=True))
    op.create_index(op.f('ix_Contents_links'), 'Contents', ['links'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Contents_links'), table_name='Contents')
    op.drop_column('Contents', 'links')
    # ### end Alembic commands ###
