"""Addtech name

Revision ID: 967a199ca0ee
Revises: 348b9d2ee57e
Create Date: 2022-08-17 10:32:00.451558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967a199ca0ee'
down_revision = '348b9d2ee57e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Technologies', sa.Column('title', sa.String(), nullable=True))
    op.create_index(op.f('ix_Technologies_title'), 'Technologies', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Technologies_title'), table_name='Technologies')
    op.drop_column('Technologies', 'title')
    # ### end Alembic commands ###
