"""Create Tables

Revision ID: b1888a3fec38
Revises: 
Create Date: 2022-08-15 13:07:38.712535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1888a3fec38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Items_description'), 'Items', ['description'], unique=False)
    op.create_index(op.f('ix_Items_title'), 'Items', ['title'], unique=False)
    op.create_table('Images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['Items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Images_url'), 'Images', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Images_url'), table_name='Images')
    op.drop_table('Images')
    op.drop_index(op.f('ix_Items_title'), table_name='Items')
    op.drop_index(op.f('ix_Items_description'), table_name='Items')
    op.drop_table('Items')
    # ### end Alembic commands ###
