"""Add image description

Revision ID: de08f73246f6
Revises: 6030a15a9779
Create Date: 2022-08-25 14:23:19.760106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de08f73246f6'
down_revision = '6030a15a9779'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Images', sa.Column('description', sa.String(), nullable=True))
    op.create_index(op.f('ix_Images_description'), 'Images', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Images_description'), table_name='Images')
    op.drop_column('Images', 'description')
    # ### end Alembic commands ###
