version: "3.8"

networks:
  app_network:
    driver: bridge

services:

  server:
    build: ./Server
    container_name: portfolio_backend_container
    networks:
      - app_network
    ports:
      - "127.0.0.1:8000:8000" 

  client:
    build: ./Client  
    container_name: portfolio_frontend_container
    networks:
      - app_network
    ports:
      - "127.0.0.1:3000:3000"
    stdin_open: true

